# This is a basic workflow to help you get started with Actions

name: Build and Deploy Gatsby

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_APP_NAME:
        required: true
      CONTENT_BRANCH:
        required: true
      GOOGLE_GTM_ID:
        required: true
      ZENDESK_CHAT_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.5.0

      - name: Create env File
        run: |
          touch .env.production
          echo GITHUB_RUN_ID=${{ github.run_id }} >> .env.production
          echo GITHUB_RUN_NUMBER=${{ github.run_number }} >> .env.production
          cat .env.production

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CONTENT_REPO: https://github.com/SSWConsulting/SSW.Website.Content
          CONTENT_BRANCH: ${{ secrets.CONTENT_BRANCH }}
          GOOGLE_GTM_ID: ${{ secrets.GOOGLE_GTM_ID }}
          ZENDESK_CHAT_KEY: ${{ secrets.ZENDESK_CHAT_KEY }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gatsby-build
          path: public
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: gatsby-build

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.AZURE_APP_NAME }}storage --auth-mode key -d '$web' -s .

      - name: logout
        run: |
          az logout
        if: always()
