name: Build - Main branch health check

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 2 * * 1-5"
  
  push:
    branches:
    - main
    - release/*

  pull_request:
    branches:
    - main

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://staging2.ssw.com.au

    steps:
      - uses: actions/checkout@v2

      # Install Node and install packages
      - name: Use Node.js
        uses: actions/setup-node@v2.5.0

      - name: Install dependencies
        run: | 
          npm install
          npm install -g gatsby-cli

      # Run gatsby build
      - name: Gatsby Build
        run: gatsby build
        env:
          CONTENT_REPO: https://github.com/SSWConsulting/SSW.Website.Content
          CONTENT_BRANCH: '${{ secrets.CONTENT_REPO }}'
